#!/bin/bash

# This hooks notifies jenkins to build application (jenkins runs on localhost in this example)
# Set user.api-key config variable to generated api key

URL="localhost:8090/job/Build-program/build"

curl -X POST "$URL" --user $(git config user.jenkins-user):$(git config user.jenkins-api-key)
