#!/bin/bash

# This hook appends commit type and hash of commit if possible (on --amend)
# Needs moreutils package

FILEPATH=$1

TYPE="None"
[ "$2" != "" ] && TYPE=$2

HASH=""
[ "$3" != "" ] && HASH=$(git rev-parse $3 | head -c8)

HASH_MSG=""
[ "$HASH" != "" ] && HASH_MSG="Previous commit hash: ${HASH}\n"

cat <(printf "Commit type: %s\n%s" "$TYPE" "$HASH" "$HASH_MSG") $FILEPATH | sponge $FILEPATH
